### ISSUE TITLE
Andi: Cannot Infer Schema with Many Columns

### ISSUE THREAD

**Issue by LtChae** [Datastillery/smartcitiesdata#1265]
Andi fails to generate a schema for this file: [Sample File](https://app.zenhub.com/files/192407200/6252834a-2d10-4d3c-8385-ed20bcdb6f10/download)

Steps to reproduce:

- Create a dataset
- Make it CSV format
- Go to data dictionary section
- Use the provided file to infer the schema

Debugging Notes:

- Does not appear to be directly related to column #
  - Though cutting down the number of columns did eventually make it work somewhere around 70, changing the column headers to smaller values allowed it to work farther.
- Does not appear to be related to the data
  - Tried it with all 1's in the columns as part of debugging

**Comment by LtChae** [comment]
```
** (FunctionClauseError) no function clause matching in anonymous fn/1 in AndiWeb.EditLiveView.DataDictionaryForm.parse_csv/1                                                                                                                                                │
│     (andi 0.76.8) lib/andi_web/live/edit_live_view/data_dictionary_form.ex:339: anonymous fn({"OBJECTID"}) in AndiWeb.EditLiveView.DataDictionaryForm.parse_csv/1                                                                                                            │
│     (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2                                                                                                                                                                                                         │
│     (andi 0.76.8) lib/andi_web/live/edit_live_view/data_dictionary_form.ex:380: AndiWeb.EditLiveView.DataDictionaryForm.generate_new_schema/3                                                                                                                                │
│     (phoenix_live_view 0.14.8) lib/phoenix_live_view/channel.ex:213: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3                                                                                                                                          │
│     (telemetry 0.4.2) /app/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3                                                                                                                                                                                           │
│     (phoenix_live_view 0.14.8) lib/phoenix_live_view/channel.ex:102: Phoenix.LiveView.Channel.handle_info/2                                                                                                                                                                  │
│     (stdlib 3.13.2) gen_server.erl:680: :gen_server.try_dispatch/4                                                                                                                                                                                                           │
│     (stdlib 3.13.2) gen_server.erl:756: :gen_server.handle_msg/6                                                                                                                                                                                                             │
│ Last message: %Phoenix.Socket.Message{event: "event", join_ref: "10", payload: %{"event" => "file_upload", "type" => "hook", "value" => %{"file" => "OBJECTID,DOCUMENT_NBR,CRASH_REPORT_LINK,CRASH_YR,CRASH_MONTH_YEAR,DISTRICT_NBR,NLFID,NLF_JUR_CD,NLF_COUNTY_CD,COUNTY_LO │
│ G_NBR,ODOT_LATITUDE_NBR,ODOT_LONGITUDE_NBR,ODOT_FIPS_CD,AREA_CODE,CRASH_DATE,CRASH_SEVERITY_CD,CRASH_TYPE_CD,DAY_IN_WEEK_CD,DISTRACTED_DRIVER_IND,FACILITY_TYPE_CD,FHWA_RDWY_DEPARTURE_IND,FREEWAY_IND,FUNCTIONAL_CLASS_CD,HOUR_OF_CRASH,INCAPAC_INJURIES_NBR,INTERCHANGE_ID │
│ ,INTERSECTION_ID_CURRENT,INTERSECTION_LEG_ID,INTERSTATE_IND,INV_LOG_NBR,INV_NLFID,IS_COMMERCIAL_RELATED,LIGHT_COND_PRIMARY_CD,LOCAL_REPORT_NUMBER_ID,MAINTENANCE_AUTHORITY_CD,MONTH_OF_CRASH,NHS_CD,NO_INJURY_REPORTED_NBR,NON_INCAPAC_INJURIES_NBR,NUMBER_OF_UNITS_NBR,ODOT │
│ _CITY_VILLAGE_TWP_NME,ODOT_CRASH_LOCATION_CD,ODOT_DIR_FROM_REF_CD,ODOT_DIV_UNDIV_IND,ODOT_INTERSECTION_REL_IND,ODOT_LANES_NBR,ODOT_MAINTAINED_HWY_IND,ODOT_MILES_FROM_REF_NBR,ODOT_REF_ROUTE_PREFIX_CD,ODOT_YOUNG_DRIVER_IND,ODPS_ADDRESS_REFERENCE,ODPS_ALCOHOL_IND,ODPS_CI │
│ TY_VILLAGE_TWP_NME,ODPS_DRUG_IND,ODPS_LOC_DIR_SUFFIX_CD,ODPS_LOC_IN_WORK_ZONE_CD,ODPS_LOC_ROAD_DIRECTION_CD,ODPS_LOC_ROAD_NME,ODPS_LOC_ROAD_SUFFIX_CD,ODPS_LOC_ROUTE_ID,ODPS_LOC_ROUTE_PREFIX_CD,ODPS_LOC_ROUTE_SUFFIX_CD,ODPS_MILEPOST_REFERENCE,ODPS_MOTORCYCLE_IND,ODPS_R │
│ EF_DIR_SUFFIX_CD,ODPS_REF_DIRECTION_CD,ODPS_REF_GIVEN,ODPS_REF_POINT_USED_CD,ODPS_REF_ROUTE_ID,ODPS_REF_ROUTE_PREFIX_CD,ODPS_REF_ROUTE_SUFFIX_CD,ODPS_REF_SUFFIX_CD,ODPS_SCHOOL_ZONE_IND,ODPS_SENIOR_DRIVER_IND,ODPS_SPEED_IND,ODPS_TOTAL_FATALITIES_NBR,ODPS_TYPE_OF_WORK_Z │
│ ONE_CD,ODPS_WORK_ZONE_IND,OPER_ACCESS_", "fileName" => "extra 3 rows.csv", "fileSize" => 3221, "fileType" => "text/csv"}}, ref: "25", topic: "lv:data_dictionary_form_editor"}
```
